services:
  - type: web
    name: netninja-proxy
    runtime: go
    plan: free
    buildCommand: go build -o proxy proxy.go
    startCommand: ./proxy
    envVars:
      - key: PORT
        value: 10000
